containers/urls.py
from django.urls import path

from . import views

app_name = "containers"
urlpatterns = [
    path("", views.search, name="index"),
    path("package/<int:pk>", views.package, name="package"),
    path("search/", views.search, name="search"),
    path("cbase/<str:cid>", views.cbase, name="cbase"),
    path("containers", views.containers, name="containers"),
]

hittade/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

from api.views import api
from start_page.views import start_page

urlpatterns = [
    path("", start_page, name="start_page"),
    path("admin/", admin.site.urls),
    path("servers/", include("servers.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("containers/", include("containers.urls")),
    path("api/", api.urls),
] + debug_toolbar_urls()

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
import servers.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("servers/", include("servers.urls")),
    path("", servers.views.search, name="index"),
 path("accounts/", include("django.contrib.auth.urls")),
] + debug_toolbar_urls()

servers/urls.py
from django.urls import path

from . import views

app_name = "servers"
urlpatterns = [
    path("", views.index, name="index"),
    # path("add/", views.add, name="add"),
    path("package/<int:pk>", views.package, name="package"),
    path("host/<int:pk>", views.host, name="host"),
    path("search/", views.search, name="search"),
    path("hosts", views.hosts, name="hosts"),
    path("logout", views.logout_view, name="logout"),
]

servers/models.py
# Create your models here.
from django.db import models


class Host(models.Model):
    id: int
    hostname = models.CharField(max_length=200)

    class Meta:
        indexes = [
            models.Index(fields=["hostname"]),
        ]


class HostDetails(models.Model):
    id: int
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    time = models.DateTimeField()
    domain = models.CharField(max_length=255, null=True, blank=True)
    osname = models.CharField(max_length=100, null=True, blank=True)
    osrelease = models.CharField(max_length=255, null=True, blank=True)
    rkr = models.CharField(max_length=255, null=True, blank=True)
    cosmosrepourl = models.CharField(max_length=255, null=True, blank=True)
    ipv4 = models.CharField(max_length=255, null=True, blank=True)
    ipv6 = models.CharField(max_length=300, null=True, blank=True)
    fail2ban = models.BooleanField(default=False)

    class Meta:
        indexes = [
            models.Index(fields=["domain"]),
            models.Index(fields=["osname", "osrelease"]),
            models.Index(fields=["ipv4"]),
            models.Index(fields=["ipv6"]),
            models.Index(fields=["fail2ban"]),
        ]
        ordering = ("-time",)


class Package(models.Model):
    id: int
    name = models.CharField(max_length=255)
    version = models.CharField(max_length=255)

    class Meta:
        unique_together = ("name", "version")
        indexes = [
            models.Index(fields=["name"]),
            models.Index(fields=["name", "version"]),
        ]


class HostPackages(models.Model):
    id: int
    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    packages = models.ManyToManyField(Package)


class ConfigValues(models.Model):
    id: int
    ctype = models.CharField(max_length=255)
    name = models.CharField()
    value = models.CharField()

    class Meta:
        unique_together = ("ctype", "name", "value")
        indexes = [
            models.Index(fields=["ctype", "name"]),
            models.Index(fields=["ctype", "name", "value"]),
        ]


class HostConfigs(models.Model):
    id: int
    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    configs = models.ManyToManyField(ConfigValues)


class ContainerImage(models.Model):
    id: int
    image = models.CharField(max_length=100)
    imageid = models.CharField(max_length=255)

    class Meta:
        indexes = [
            models.Index(fields=["image"]),
            models.Index(fields=["imageid"]),
        ]


class HostContainers(models.Model):
    id: int
    time = models.DateTimeField()
    host = models.ForeignKey(Host, on_delete=models.CASCADE)
    containers = models.ManyToManyField(
        ContainerImage,
        through="HostContainersThrough",
        through_fields=("hc", "container"),
    )


class HostContainersThrough(models.Model):
    id: int
    hc = models.ForeignKey(HostContainers, on_delete=models.CASCADE)
    container = models.ForeignKey(ContainerImage, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

servers/forms.py
from django import forms


search_choices = {"package": "Package", "host": "Host"}


class PackageForm(forms.Form):
    package_name = forms.CharField(label="Package Name", max_length=255)
    package_version = forms.CharField(
        label="Package Version", max_length=255, required=False
    )


class SearchForm(forms.Form):
    search = forms.CharField(label="Search", max_length=255)
    stype = forms.ChoiceField(
        label="",
        choices=search_choices.items(),
        required=False,
        widget=forms.Select(attrs={"class": "select", "id": "standard-select"}),
    )

servers/views.py
import json
from typing import Any, DefaultDict

from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import OuterRef, Subquery

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt

from .forms import SearchForm
from .models import (
    ConfigValues,
    Host,
    HostConfigs,
    HostContainers,
    HostDetails,
    HostPackages,
    Package,
)
from .utils import generate_host_configurations_dict, get_osdetails


def logout_view(request):
    # FIXME: Handle CSRF token validation
    logout(request)
    return redirect("/")


@login_required
@permission_required("servers.view_host", raise_exception=True)
def package(request, pk):
    package = Package.objects.get(pk=pk)
    latest_host_details_subquery = (
        HostPackages.objects.filter(host=OuterRef("pk"))
        .order_by("-time")
        .values("pk")[:1]
    )
    hosts_with_package = Host.objects.filter(
        hostpackages__pk__in=Subquery(latest_host_details_subquery),
        hostpackages__packages=package,
    ).distinct()
    return render(
        request,
        "servers/package.html",
        {
            "title": f"Package: {package.name} - {package.version}",
            "package": package,
            "hosts": hosts_with_package,
        },
    )


@login_required
@permission_required("servers.view_host", raise_exception=True)
def host(request, pk):
    host = Host.objects.get(pk=pk)
    host_packages = HostPackages.objects.filter(host=host).order_by("-time")[0]
    try:
        host_configs = HostConfigs.objects.filter(host=host).order_by("-time")[0]
    except IndexError:
        host_configs = []
    host_containers = HostContainers.objects.filter(host=host).order_by("-time")[0]
    cdetails = host_containers.hostcontainersthrough_set.all().prefetch_related()
    details = HostDetails.objects.filter(host=host).order_by("-time")[0]

    if host_configs:
        config_from_db = host_configs.configs.all()
    else:
        config_from_db = []

    return render(
        request,
        "servers/host.html",
        {
            "title": host.hostname,
            "host": host,
            "packages": host_packages.packages.all(),
            "containers": cdetails,
            "details": details,
            "configurations": generate_host_configurations_dict(config_from_db),
        },
    )


@login_required
@permission_required("servers.view_host", raise_exception=True)
def search(request):
    # if this is a POST request we need to process the form data
    data = {}
    text = ""
    stype = ""

    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            text = form.data["search"]
            stype = form.data["stype"]
            if form.data["stype"] == "package":
                search_text = form.data["search"]
                words = search_text.split(" ")
                package_name = words[0]
                if len(words) == 1:
                    packages = Package.objects.filter(name__icontains=package_name)
                else:
                    package_version = words[1]
                    packages = Package.objects.filter(
                        name__icontains=package_name, version__icontains=package_version
                    )
                data["packages"] = packages
            else:
                search_text = form.data["search"]
                search_text = search_text.strip()
                hosts = Host.objects.filter(hostname__icontains=search_text)
                data["hosts"] = hosts
    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchForm()

    return render(
        request,
        "servers/search.html",
        {
            "title": "Search",
            "form": form,
            "data": data,
            "text": text,
            "stype": stype,
        },
    )


@login_required
@permission_required("servers.view_host", raise_exception=True)
def hosts(request):
    "To show list of all hosts."
    hosts = Host.objects.all().order_by("hostname")
    return render(request, "servers/hosts.html", {"title": "All hosts", "hosts": hosts})


@login_required
@permission_required("servers.view_host", raise_exception=True)
def index(request):
    # osdetails: dict[Any, Any] = get_osdetails()
    # # HACK: To stop any error on the view for missing cache
    # if not osdetails:
    # osdetails = {}
    # data = {}
    # for k, v in osdetails.items():
    # data[k.decode("utf-8")] = json.loads(v)
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        ip = x_forwarded_for.split(",")[0]
    else:
        ip = request.META.get("REMOTE_ADDR")
    print(ip)
    data = DefaultDict(list)
    hosts_with_all_details = (
        Host.objects.order_by("-id").distinct().prefetch_related("hostdetails_set")
    )
    for host in hosts_with_all_details:
        ld = host.hostdetails_set.first()  # pyright: ignore
        osdetails = f"{ld.osname}-{ld.osrelease}"
        data[osdetails].append((host.hostname, host.id))

    return render(
        request, "servers/index.html", {"title": "Servers", "osdetails": dict(data)}
    )

servers/templates/servers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css " rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>{% block title %}Hittade Server{% endblock %}</title>
</head>


<body>
    <nav class="navbar navbar-expand-md bg-primary navbar-dark">
        <div class="container">
            <a href="/" class="navbar-brand">Hittade</a>
            <button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" class="navbar-toggler">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link ">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'servers:search' %}" class="nav-link">Search</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'servers:hosts' %}" class="nav-link">List of all hosts</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'servers:logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-link">Logout</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main>
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div
                        class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/"
                            class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Menu</span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                            id="menu">
                            <li>

                                <a href="{% url 'servers:search' %}" class="nav-link px-0"> <span
                                        class="d-none d-sm-inline text-white">Search hosts</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url 'servers:hosts' %}" class="nav-link px-0"> <span
                                                class="d-none d-sm-inline text-white">All hosts</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'containers:search' %}" class="nav-link px-0"> <span
                                        class="d-none d-sm-inline text-white">Search containers</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url 'containers:containers' %}" class="nav-link px-0"> <span
                                                class="d-none d-sm-inline text-white">All containers</span>
                                        </a>
                                    </li>

                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col py-3">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>


    </main>
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js "></script>
</body>

</html>

servers/templates/servers/host.html
{% extends "servers/base.html" %}
{% block title %}Host details{% endblock %}

{% block content %}
<div class="container-md m-5">
    <p class="h2"> You are viewing details of
        {{ host.hostname }}
    </p>
</div>
<div class="container-md m-5">
    <h3>OS details</h3>
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>OS Name</td>
                <td>{{ details.osname }}</td>
            </tr>
            <tr>
                <td>OS Release</td>
                <td>{{ details.osrelease }}</td>
            </tr>
            <tr>
                <td>Domain</td>
                <td>{{ details.domain }}</td>
            </tr>
            <tr>
                <td>Fail2Ban</td>
                <td>{% if details.fail2ban %} <span class="badge text-bg-success">On</span><span
                        class="visually-hidden">On</span>
                    {% else %} <span class="badge text-bg-warning">Off</span><span class="visually-hidden">Off</span>
                    {% endif %}</td>
            </tr>
            <tr>
                <td>IPv4</td>
                <td>{{ details.ipv4 }}</td>
            </tr>
            <tr>
                <td>IPv6</td>
                <td>{{ details.ipv6 }}</td>
            </tr>
            <tr>
                <td>Kernel version</td>
                <td>{{ details.rkr }}</td>
            </tr>


        </tbody>
    </table>

</div>
<div class="container-md m-5">
    <h3>Configuration details</h3>
    <table class="table table-striped">
        <tbody>
            {% for config in configurations %}
            <tr>
                <td>{{ config.ctype }}</td>
                <td>{{ config.name }}</td>
                <td>{{ config.value }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div class="container-md m-5">
    <div class="row">
        <div class="col col-1">
            <svg xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 640 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.-->
                <path
                    d="M349.9 236.3h-66.1v-59.4h66.1v59.4zm0-204.3h-66.1v60.7h66.1V32zm78.2 144.8H362v59.4h66.1v-59.4zm-156.3-72.1h-66.1v60.1h66.1v-60.1zm78.1 0h-66.1v60.1h66.1v-60.1zm276.8 100c-14.4-9.7-47.6-13.2-73.1-8.4-3.3-24-16.7-44.9-41.1-63.7l-14-9.3-9.3 14c-18.4 27.8-23.4 73.6-3.7 103.8-8.7 4.7-25.8 11.1-48.4 10.7H2.4c-8.7 50.8 5.8 116.8 44 162.1 37.1 43.9 92.7 66.2 165.4 66.2 157.4 0 273.9-72.5 328.4-204.2 21.4 .4 67.6 .1 91.3-45.2 1.5-2.5 6.6-13.2 8.5-17.1l-13.3-8.9zm-511.1-27.9h-66v59.4h66.1v-59.4zm78.1 0h-66.1v59.4h66.1v-59.4zm78.1 0h-66.1v59.4h66.1v-59.4zm-78.1-72.1h-66.1v60.1h66.1v-60.1z" />
            </svg>
        </div>
        <div class="col col-11">
            <h3 class="md-2">Running containers: <span class="badge text-bg-info">{{ containers|length }}
                </span></h3>
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Container Image</th>
                <th scope="col">Image ID</th>
                <th scope="col">Name</th>
            </tr>
        </thead>
        <tbody>
            {% for hc in containers %}
            <tr>
                <td>{{ hc.container.image }}</td>
                <td>{{ hc.container.imageid }}</td>
                <td>{{ hc.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


</div>
<div class="container-md m-5">
    <p class="h3">Current package list</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Package name</th>
                <th scope="col">Package version</th>
            </tr>
        </thead>
        <tbody>
            {% for package in packages %}
            <tr>
                <td><a href="{% url 'servers:package' package.id %}">{{ package.name }}</a></td>
                <td>{{ package.version }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

<!-- It is running Kernel {{ host.rkr }} using {{ host.osname }} {{ host.osrelease }}.

<p>Domain: {{ host.domain }}</p>
<p>Cosmos URL: {{ host.cosmosrepourl }}</p> -->

servers/templates/servers/hosts.html
{% extends "servers/base.html" %}
{% block title %}All hosts{% endblock %}


{% block content %}
<div class="m-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Host name</th>
            </tr>
        </thead>
        <tbody>
            {% for host in hosts %}
            <tr>
                <td> <a href="{% url 'servers:host' host.id %}">{{ host.hostname }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

servers/templates/servers/index.html
{% extends "servers/base.html" %}
{% block title %}Welcome to server/host details page{% endblock %}

{% block content %}
<div class="container-md m-5">
    {% for osd, values in osdetails.items %}
    <details>
        <summary class="h2">{{ osd }}</summary>
        <div class="container-md m5">
            {% for value in values %}
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'servers:host' value.1 %}"> {{ value.0 }}</a></li>
            </ul>
            {% endfor %}
        </div>
    </details>
    {% endfor %}
</div>
{% endblock %}

servers/templates/servers/package.html
{% extends "servers/base.html" %}
{% block title %}Package details{% endblock %}

{% block content %}
<div class="container-md">
    <h3 class="m-5">Hosts with package: {{ package.name }} - {{ package.version }}</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Host name</th>
            </tr>
        </thead>
        <tbody>
            {% for host in hosts %}
            <tr>
                <td><a href="{% url 'servers:host' host.id %}">{{ host.hostname }} </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

servers/templates/servers/search.html
{% extends "servers/base.html" %}
{% block title %}Search Page{% endblock %}


{% block content %}
<header class="m-5">
    <form action="{% url 'servers:search' %}" method="post">
        {% csrf_token %}
        <div class="col-6 offset-3">
            <div class="input-group input-group-lg">
                <span class="input-group-text rounded-start-5">
                    <i class="fas fa-search"></i>
                </span>
                <input type="text" class="form-control" id="id_serach" name="search">
                <div class="col-xs-1">
                    <select class="form-select form-select-lg rounded-end-5" aria-label="Searching for package or host"
                        name="stype" id="stype">
                        <option value="package">Package</option>
                        <option value="host">Host</option>
                    </select>
                </div>
            </div>
        </div>

    </form>

</header>


<div class="m-5">
    {% if data.packages %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Version</th>
            </tr>
        </thead>
        <tbody>
            {% for package in data.packages %}
            <tr>
                <td><a href="{% url 'servers:package' package.id %}">{{ package.name }} </a></td>
                <td>{{ package.version }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

    {% if data.hosts %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Host name</th>
            </tr>
        </thead>
        <tbody>
            {% for host in data.hosts %}
            <tr>
                <td> <a href="{% url 'servers:host' host.id %}">{{ host.hostname }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>

{% endblock %}