hittade/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

from api.views import api
from start_page.views import start_page

urlpatterns = [
    path("", start_page, name="start_page"),
    path("admin/", admin.site.urls),
    path("servers/", include("servers.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("containers/", include("containers.urls")),
    path("api/", api.urls),
] + debug_toolbar_urls()

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
import servers.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("servers/", include("servers.urls")),
    path("", servers.views.search, name="index"),
 path("accounts/", include("django.contrib.auth.urls")),
] + debug_toolbar_urls()

servers/urls.py
from django.urls import path

from . import views

app_name = "servers"
urlpatterns = [
    path("", views.index, name="index"),
    # path("add/", views.add, name="add"),
    path("package/<int:pk>", views.package, name="package"),
    path("host/<int:pk>", views.host, name="host"),
    path("search/", views.search, name="search"),
    path("hosts", views.hosts, name="hosts"),
    path("logout", views.logout_view, name="logout"),
]

start_page/views.py
from collections import Counter
from django.shortcuts import render
from django.http import HttpRequest

from servers.models import Host

def start_page(request: HttpRequest):
    if not request.user.is_authenticated:
        return render(request, "start_page/public.html")

    context = {}

    if request.user.has_perm("servers.view_host"):
        hosts = Host.objects.all()

        os_names = []
        for host in Host.objects.order_by("-id").distinct():
            if (ld := host.hostdetails_set.first()):
                os_names.append(f"{ld.osname}-{ld.osrelease}")
        
        most_common_os, most_common_os_count = Counter(os_names).most_common(1)[0]

        os_count = len(list(set(os_names)))

        packages = []
        for host in Host.objects.order_by("-id").distinct():
            for package in host.hostpackages_set.first().packages.all():
                packages.append(f"{package.name}-{package.version}")

        most_common_package, most_common_package_count = Counter(packages).most_common(1)[0]

        package_count = len(list(set(packages)))

        context["servers"] = {
            "count": len(hosts),
            "recents": hosts.order_by("-id")[:10],
            "os_count": os_count,
            "most_common_os": most_common_os,
            "most_common_os_count": most_common_os_count,
            "package_count": package_count,
            "most_common_package": most_common_package,
            "most_common_package_count": most_common_package_count,
        }

    return render(
        request=request, 
        template_name="start_page/authenticated.html",
        context=context
    )

start_page/templates/start_page/authenticated.html
{% extends "dashboard.html" %}

{% block sidebar %}
<div class="ht-notice -info" aria-labelledby="access-note-heading">
    <h2 id="access-note-heading" class="ht-heading">Note:</h2>
    <p class="ht-text -s">After you login for the first time, you will have to inform Kushal (for the test server) to give you access.</p>
</div>
{% endblock %}

{% block main %}
    <div class="ht-content">
        <h1 class="ht-heading -xl _mb">Hittade Server</h1>
        <div class="ht-grid -col:2">
            {% if servers %}
                <div class="ht-card -gray-light" aria-labelledby="servers-info">
                    <div class="ht-flex -middle -space-between">
                        <h2 id="servers-info" class="ht-heading -l">Servers</h2>
                        <a href="{% url 'servers:hosts' %}">View All</a>
                    </div>
                    <div class="ht-container">
                        <h3 class="ht-heading">At a glance</h3>
                        <p class="ht-text -s">
                            The <strong>{{ servers.count }}</strong> servers in <em>Hittade</em> run a total of 
                            <strong>{{ servers.os_count }}</strong> different operating systems. The most common is 
                            <em>{{ servers.most_common_os }}</em>, used by <strong>{{ servers.most_common_os_count }}</strong> servers. 
                            Across all servers, <strong>{{ servers.package_count }}</strong> software packages are in use, with 
                            <em>{{ servers.most_common_package }}</em> being the most widely deployed, running on 
                            <strong>{{ servers.most_common_package_count }}</strong> machines.
                        </p>
                    </div>
                    <div>
                        <h3 class="ht-heading">Recently added</h3>
                        <ul class="ht-list">
                            {% for host in servers.recents %}
                            <li class="ht-text -s">
                                <a href="{% url 'servers:host' host.id %}">{{ host.hostname }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

start_page/templates/start_page/public.html
{% extends "base.html" %}

{% block body %}
    <div class="ht-content -center -middle -narrow">
        <figure class="ht-flex -center">
            <img src="/static/img/sunet.svg" width="130" alt="Sunet">
        </figure>
        <h1 class="ht-heading -xxl -center">Hittade server</h1>
        <div class="ht-notice -info" aria-labelledby="access-note-heading">
            <h2 id="access-note-heading" class="ht-heading">Note:</h2>
            <p class="ht-text -s">After you login for the first time, you will have to inform Kushal (for the test server) to give you access.</p>
        </div>
        <div class="ht-buttons -center">
            <a href="{% url 'servers:index' %}" class="ht-button -primary">Log in</a>
        </div>
    </div>
{% endblock %}