containers/urls.py
from django.urls import path

from . import views

app_name = "containers"
urlpatterns = [
    path("", views.search, name="index"),
    path("package/<int:pk>", views.package, name="package"),
    path("search/", views.search, name="search"),
    path("cbase/<str:cid>", views.cbase, name="cbase"),
    path("containers", views.containers, name="containers"),
]

hittade/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

from api.views import api
from start_page.views import start_page

urlpatterns = [
    path("", start_page, name="start_page"),
    path("admin/", admin.site.urls),
    path("servers/", include("servers.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("containers/", include("containers.urls")),
    path("api/", api.urls),
] + debug_toolbar_urls()

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
import servers.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("servers/", include("servers.urls")),
    path("", servers.views.search, name="index"),
 path("accounts/", include("django.contrib.auth.urls")),
] + debug_toolbar_urls()

servers/urls.py
from django.urls import path

from . import views

app_name = "servers"
urlpatterns = [
    path("", views.index, name="index"),
    # path("add/", views.add, name="add"),
    path("package/<int:pk>", views.package, name="package"),
    path("host/<int:pk>", views.host, name="host"),
    path("search/", views.search, name="search"),
    path("hosts", views.hosts, name="hosts"),
    path("logout", views.logout_view, name="logout"),
]

containers/models.py
from django.db import models

# Create your models here.

class ContainerTags(models.Model):
    tag = models.CharField(max_length=255)
    fullname = models.CharField(max_length=255)
    class Meta:
        indexes = [
            models.Index(fields=["tag"]),
            models.Index(fields=["fullname"]),
        ]

class ContainerPackage(models.Model):
    provider = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    version = models.CharField(max_length=255)

    class Meta:
        unique_together = ("name", "version", "provider"),
        indexes = [
            models.Index(fields=["name"]),
            models.Index(fields=["name", "version"]),
            models.Index(fields=["name", "version","provider" ]),
        ]

class ContainerBase(models.Model):
    cid = models.CharField(max_length=255)
    cname = models.CharField(max_length=255)
    osname = models.CharField(max_length=255, null=True)
    osversionid = models.CharField(max_length=255, null=True)
    time = models.DateTimeField()
    ctime = models.DateTimeField()
    tags = models.ManyToManyField(ContainerTags)
    packages = models.ManyToManyField(ContainerPackage)

    class Meta:
        indexes = [
            models.Index(fields=["cid"]),
            models.Index(fields=["osname", "osversionid"]),
        ]    

containers/forms.py
from django import forms


search_choices = {"package": "Package", "container": "Container"}


class PackageForm(forms.Form):
    package_name = forms.CharField(label="Package Name", max_length=255)
    package_version = forms.CharField(
        label="Package Version", max_length=255, required=False
    )


class SearchForm(forms.Form):
    search = forms.CharField(label="Search", max_length=255)
    stype = forms.ChoiceField(
        label="",
        choices=search_choices.items(),
        required=False,
        widget=forms.Select(attrs={"class": "select", "id": "standard-select"}),
    )

containers/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import OuterRef, Subquery
from django.core.paginator import Paginator
import datetime
import pytz
from .forms import SearchForm
from .models import ContainerPackage, ContainerTags, ContainerBase
from .utils import latest_containers
# Create your views here.


@login_required
@permission_required("containers.view_containerbase", raise_exception=True)
def index(request):
    return redirect(search)

@login_required
@permission_required("containers.view_containerbase", raise_exception=True)
def package(request, pk):
    package = ContainerPackage.objects.get(pk=pk)
    latest = latest_containers()
    cbs = ContainerBase.objects.filter(packages=package, id__in=latest).prefetch_related()

    # Now construct the data
    result = []
    for cb in cbs:
        data = {}
        for tag in cb.tags.all():
            data["fullname"] = tag.fullname
            data["cid"] = cb.cid
        result.append(data)

    return render(
        request,
        "containers/package.html",
        {
            "title": f"Package details",
            "package": package, 
            "data": result,
        },
    ) 


@login_required
@permission_required("containers.view_containerbase", raise_exception=True)
def cbase(request, cid):
    "Shows details of a specific container image based on it's container ID."
    try:
        cb = ContainerBase.objects.filter(cid=cid)[0]
    except ContainerBase.DoesNotExist:
        return render(request, "containers/container.html", {"error": "Container not found."})
    
    return render(
        request, 
        "containers/container.html", 
        {
            "title": f"Container details",
            "cb": cb, 
            "tags": cb.tags.all(), 
            "packages": cb.packages.all(),
        }
    )

@login_required
@permission_required("containers.view_containerbase", raise_exception=True)
def containers(request):
    cbs = ContainerBase.objects.prefetch_related("tags").order_by("-ctime")
    paginator = Paginator(cbs, 50)

    page_number = request.GET.get("page", 1)
    page_number = int(page_number)
    if page_number < 1:
        page_number = 1
    elif page_number > paginator.num_pages:
        page_number = paginator.num_pages

    page = paginator.page(page_number)
    result = []
    for cb in page.object_list:
        result.append({"fullname": cb.tags.all()[0].fullname, "cid": cb.cid})
    
    return render(
        request, 
        "containers/containers.html", 
        {
            "title": f"All container images",
            "cbs": result, 
            "page": page,
        }
    )


@login_required
@permission_required("containers.view_containerbase", raise_exception=True)
def search(request):
    # if this is a POST request we need to process the form data
    data = {}
    text = ""
    stype = ""
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = SearchForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            text = form.data["search"]
            stype = form.data["stype"]
            if form.data["stype"] == "package":
                search_text = form.data["search"]
                words = search_text.split(" ")
                package_name = words[0]
                if len(words) == 1:
                    packages = ContainerPackage.objects.filter(name__icontains=package_name)
                else:
                    package_version = words[1]
                    packages = ContainerPackage.objects.filter(
                        name__icontains=package_name, version__icontains=package_version
                    )
                data["packages"] = packages
            else:
                search_text = form.data["search"]
                search_text = search_text.strip()
                container_tags  = ContainerTags.objects.filter(fullname__icontains=search_text)
                container_bases = ContainerBase.objects.filter(tags__in=container_tags)
                # Now create the list of containers with proper tags.
                # There can be more than one container+tag combination with same value.
                results = []
                for cb in container_bases:
                    result = {}
                    for tag in cb.tags.all():
                        result["fullname"] = tag.fullname
                        result["cid"] = cb.cid
                    results.append(result)

                data["cbs"] = results
    # if a GET (or any other method) we'll create a blank form
    else:
        form = SearchForm()

    return render(
        request, 
        "containers/search.html", 
        {
            "title": f"Container search",
            "form": form, 
            "data": data, 
            "text": text,
            "stype": stype,
        }
    )

containers/templates/containers/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css " rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>{% block title %}Hittade Server{% endblock %}</title>
</head>


<body>
    <nav class="navbar navbar-expand-md bg-primary navbar-dark">
        <div class="container">
            <a href="/" class="navbar-brand">Hittade</a>
            <button type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" class="navbar-toggler">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="#" class="nav-link ">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'containers:search' %}" class="nav-link">Search</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'containers:containers' %}" class="nav-link">List of all containers</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'servers:logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-link">Logout</button>
                        </form>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <main>
        <div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div
                        class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/"
                            class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Menu</span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start"
                            id="menu">
                            <li>

                                <a href="{% url 'servers:search' %}" class="nav-link px-0"> <span
                                        class="d-none d-sm-inline text-white">Search hosts</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url 'servers:hosts' %}" class="nav-link px-0"> <span
                                                class="d-none d-sm-inline text-white">All hosts</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="{% url 'containers:search' %}" class="nav-link px-0"> <span
                                        class="d-none d-sm-inline text-white">Search containers</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a href="{% url 'containers:containers' %}" class="nav-link px-0"> <span
                                                class="d-none d-sm-inline text-white">All containers</span>
                                        </a>
                                    </li>

                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col py-3">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>


    </main>
    <script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js "></script>
</body>

</html>

containers/templates/containers/container.html
{% extends "containers/base.html" %}
{% block title %}Container details{% endblock %}

{% block content %}
{% if error %}
<div class="m-5">
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
</div>

{% else %}
<div class="container-md m-5">
    <div class="container-md md-5">
        <p class="h2"> You are viewing details of the image with existing tag(s):
        </p>
    </div>
    {% for tag in tags %}
    <p class="h3 mt-5">{{ tag.fullname }}</p>
    {% endfor %}
</div>
<div class="container-md m-5">
    <h3>OS details</h3>
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>OS Name</td>
                <td>{{ cb.osname }}</td>
            </tr>
            <tr>
                <td>OS Version</td>
                <td>{{ cb.osversionid }}</td>
            </tr>
            <tr>
                <td>SHA256</td>
                <td>
                    {{ cb.cid }}
                </td>
            </tr>
            <tr>
                <td>Created At</td>
                <td>
                    {{ cb.ctime|date:"r" }}
                </td>
            </tr>

        </tbody>
    </table>

</div>
<div class="container-md m-5">
    <p class="h3">Package list</p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Package name</th>
                <th scope="col">Package version</th>
                <th scope="col">Provider</th>
            </tr>
        </thead>
        <tbody>
            {% for package in packages %}
            <tr>
                <td><a href="{% url 'containers:package' package.id %}">{{ package.name }}</a></td>
                <td>{{ package.version }}</td>
                <td>{{ package.provider }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% endblock %}

containers/templates/containers/containers.html
{% extends "containers/base.html" %}
{% block title %}All container images{% endblock %}


{% block content %}
<div class="m-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Container</th>
            </tr>
        </thead>
        <tbody>
            {% for cb in cbs %}
            <tr>
                <td> <a href="{% url 'containers:cbase' cb.cid %}">{{ cb.fullname }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if page.has_other_pages %}
    {% if page.has_previous %}
    <a href="{% url 'containers:containers' %}?page={{page.previous_page_number}}">Prev</a> &nbsp;&nbsp;&nbsp;
    {% endif %}
    {% if page.has_next %}
    <a href="{% url 'containers:containers' %}?page={{page.next_page_number}}">Next</a>
    {% endif %}
    {% endif %}
</div>

{% endblock %}

containers/templates/containers/package.html
{% extends "containers/base.html" %}
{% block title %}Package details{% endblock %}

{% block content %}
<div class="container-md">
    <h3 class="m-5">Latest container tags with package:
        {{ package.name }} - {{ package.version }} - {{ package.provider }}
    </h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Container name</th>
            </tr>
        </thead>
        <tbody>
            {% for cb in data %}
            <tr>
                <td><a href="{% url 'containers:cbase' cb.cid %}">{{ cb.fullname }} </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

containers/templates/containers/search.html
{% extends "containers/base.html" %}
{% block title %}Search Page{% endblock %}


{% block content %}
<header class="m-5">
    <div class="md-5">
        <h2 class="d-flex align-items-center justify-content-center">Containers Search</h2>
    </div>
    <form action="{% url 'containers:search' %}" method="post">
        {% csrf_token %}
        <div class="col-6 offset-3">
            <div class="input-group input-group-lg">
                <span class="input-group-text rounded-start-5">
                    <i class="fas fa-search"></i>
                </span>
                <input type="text" class="form-control" id="id_serach" name="search">
                <div class="col-xs-1">
                    <select class="form-select form-select-lg rounded-end-5" aria-label="Searching for package or host"
                        name="stype" id="stype">
                        <option value="container">Container</option>
                        <option value="package">Package</option>
                    </select>
                </div>
            </div>
        </div>

    </form>

</header>


<div class="m-5">
    {% if data.packages %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Version</th>
            </tr>
        </thead>
        <tbody>
            {% for package in data.packages %}
            <tr>
                <td><a href="{% url 'containers:package' package.id %}">{{ package.name }} </a></td>
                <td>{{ package.version }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}

    {% if data.cbs %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Container</th>
            </tr>
        </thead>
        <tbody>
            {% for cb in data.cbs %}
            <tr>
                <td> <a href="{% url 'containers:cbase' cb.cid %}">{{ cb.fullname }}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>

{% endblock %}